feat(plugins): Adding CCS plugin for ReDS and Plexos translation
NREL/R2X pull request #95
Opened 2024-12-09 17:26 UTC by pesap

List of changes
- New plugin `ccs_credit` that adds `UoS charge` for plexos to eligible CCS technologies,
- New `EXT_PROPERTIES` variable that specify nested properties on the EXT that will be exported to plexos
- New export function to pop a given key from a dictionary. Useful for extracting stuff from the ext field,
- Added files relevant for the CCS plugin on the `reeds_us_mapping.json`
- New simplified `Configuration` handling,

2025-01-10 19:04 UTC, JensZack commented on src/r2x/exporter/plexos.py
> +        logger.debug("Using {} for reports.")
Should this have an argument passed, probably fpath or report_objects?

2025-01-10 19:05 UTC, JensZack commented on src/r2x/exporter/utils.py
> +    >>> flatten_selected_keys(d, ["x"])
These examples aren't the same function name, and use a different set of arguments.

2025-01-10 19:08 UTC, JensZack commented on src/r2x/exporter/utils.py
> +    extracted_keys = {key: value for key, value in d[key].items() if key in keys_to_extract}
This doesn't appear to join the inner and outer keys ("x", "min" -> "x_min"), and the use of key from the function parameter from the dict items is really confusing. I think this could be:
`{f"{key}_{inner_key}": value for inner_key, value in d[key].items() if key in keys_to_extract}`

2025-01-10 19:09 UTC, JensZack commented on src/r2x/exporter/utils.py
> +    extracted_keys = {key: value for key, value in d[key].items() if key in keys_to_extract}
Also this function and the function above, apply_flatten_key (not changed in this MR), both fail doctest on their examples.

2025-01-10 19:09 UTC, JensZack commented on src/r2x/parser/reeds.py
> +        # month_of_hour = np.array(
should this be removed?

2025-01-10 19:12 UTC, JensZack commented on src/r2x/parser/reeds.py
> +            # hourly_time_series = np.zeros(len(month_of_hour), dtype=float)
More comments that probably need to be cleaned up.

2025-01-10 19:14 UTC, JensZack commented on src/r2x/parser/reeds.py
> +                daily_max_budget = month_max_budget / (row["hrs"] / 24)
what is the purpose of smoothing out the daily budgets to the monthly max?

2025-01-10 19:18 UTC, JensZack commented on src/r2x/plugins/ccs_credit.py
> +        msg = "Plugin `ccs_credit.py` is not compatible with a model that is not Plexos or ReEDs input."
should this if statement be checking if the input model is in ["plexos", "reeds-us"]? or does the message need to change to reflect the input requirements?

2025-01-14 00:29 UTC, JensZack requested changes

2025-01-14 00:29 UTC, JensZack commented on src/r2x/config_models.py
> +    PRAS = "PRAS"
Why is PRAS in the Models enum if it doesn't have a base config?

2025-01-14 00:29 UTC, JensZack commented on src/r2x/config_scenario.py
> +    user_dict: dict[str, Any] | None = None
Can you add this attribute to the docstring?

2025-01-14 00:29 UTC, JensZack commented on src/r2x/config_scenario.py
> +        # Overload configuration if the key appear on the config file
Can you specify in which way the configs are overloaded?

2025-01-14 00:29 UTC, JensZack commented on src/r2x/config_scenario.py
> +    input_config: BaseModelConfig | None = None
how do optional config models work? I don't understand how r2x could work without both an input and output model

2025-01-14 00:29 UTC, JensZack commented on src/r2x/config_scenario.py
> +    """r2x.config_scenariouration manager that wraps multiple Scenario instances.
looks like a typo

2025-01-14 00:29 UTC, JensZack commented on src/r2x/config_utils.py
> +            msg = f"Unsupported model: {model_enum}. Supported models: {list(MODEL_CONFIGS.keys())}"
This msg would indicate that infrasys and reeds are supported when they are not.

2025-01-14 18:19 UTC, pesap commented on src/r2x/exporter/plexos.py
> +        logger.debug("Using {} for reports.")
Yea. That could work better.

2025-01-14 18:24 UTC, pesap commented on src/r2x/config_models.py
> +    PRAS = "PRAS"
Future work!

2025-01-14 18:31 UTC, pesap commented on src/r2x/config_scenario.py
> +    user_dict: dict[str, Any] | None = None
Done.

2025-01-14 18:40 UTC, pesap commented on src/r2x/config_scenario.py
> +        # Overload configuration if the key appear on the config file
Done.

2025-01-14 18:53 UTC, pesap commented on src/r2x/config_scenario.py
> +    """r2x.config_scenariouration manager that wraps multiple Scenario instances.
Done.

2025-01-14 18:54 UTC, pesap commented on src/r2x/plugins/ccs_credit.py
> +        msg = "Plugin `ccs_credit.py` is not compatible with a model that is not Plexos or ReEDs input."
This is a good question. The if constraint is for a given translation workflow where the plugin is tie to. In this case (reeds-US -> plexos). Is there a better way of doing this?

2025-01-14 19:06 UTC, pesap commented on src/r2x/exporter/utils.py
> +    >>> flatten_selected_keys(d, ["x"])
Bad copy paste.

2025-01-14 19:17 UTC, pesap commented on src/r2x/exporter/utils.py
> +    extracted_keys = {key: value for key, value in d[key].items() if key in keys_to_extract}
The problem with this is that we need to preserver the original key: value pairs.

2025-01-14 21:07 UTC, pesap commented on src/r2x/config_utils.py
> +            msg = f"Unsupported model: {model_enum}. Supported models: {list(MODEL_CONFIGS.keys())}"
Added a new class that will show the right model supported

2025-01-15 02:09 UTC, merged